#
# Automatically generated make config: don't edit
# Mozart SDK configure
#

CPU_MODEL=X1000

#PRODUCT_NAME=canna_v1.0_ap6255NS
PRODUCT_NAME=canna_v1.0_ap6255
SUPPORT_WIFI_MODULE=bcm_ap6255

SUPPORT_BT_MODULE=bcm_ap6255

SUPPORT_BT_HCI_DEV=/dev/ttyS0

SUPPORT_WEBRTC=1

AUDIO_DEV_PLAYBACK=/dev/dsp
AUDIO_DEV_RECORD=/dev/dsp3
AUDIO_DEV_PCM=/dev/dsp1
AUDIO_DEV_SPDIFOUT=/dev/dsp2

SUPPORT_DMR=1

SUPPORT_AIRPLAY=1

SUPPORT_LOCALPLAYER=1

SUPPORT_APPSERVER=1

SUPPORT_INGENICPLAYER=1

SUPPORT_VR=aispeech

SUPPORT_VR_WAKEUP=vr_wakeup_voice_key_mix

SUPPORT_SONG_SUPPLYER=aispeech

SUPPORT_TTS=aispeech

SUPPORT_ADB_DEBUG=1

SUPPORT_FS=cramfs

SUPPORT_USRDATA=jffs2

FLASH_TYPE=spinor
FLASH_PAGE_SIZE=0x100
FLASH_ERASE_BLOCK_SIZE=0x8000
FLASH_USRDATA_PADSIZE=0xa0000
